apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: nginx-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: pod-test
  template:
    metadata:
      labels:
        app: pod-test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: service-test
  labels:
    app: nginx-service
spec:
  selector:
    app: pod-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80